config/routes.rb
Rails.application.routes.draw do
  root "urls#index"
  resources :urls, only: [:index, :new, :create]
  resources :urls, :only => ['show'], :path => '/'
end

app/models/url.rb
require 'net/http'
class Url < ActiveRecord::Base
  #validates :shorten_url, presence: true
  validates :origin_url, presence: true, url: true
  validates :token, uniqueness: true, allow_blank: true, length: { is: 8 }
  validate :check_url_valid

  CHARSETS = ('a'..'z').to_a + ('A'..'Z').to_a + (0..9).to_a
  UNIQUE_KEY_LENGTH = 8

  before_create :generate_or_use_token

  protected

  def check_url_valid
    # if origin_url is not a valid url, then no need to check
    return if self.errors[:origin_url].present?

    # get through by test it
    result = Net::HTTP.get_response(URI.parse(self.origin_url))
    return if result.is_a?(Net::HTTPSuccess) || result.is_a?(Net::HTTPRedirection)
    errors.add(:origin_url, :not_pass_through)
  end

  def generate_or_use_token
    return if token.present?
    token = self.class.generate_unique_token
    self.token = self.class.generate_unique_token
  end

  def self.generate_unique_token
    token = gen_token
    while self.where(token: token).first do
      token = gen_token
    end
    token
  end

  def self.gen_token
    (0...Url::UNIQUE_KEY_LENGTH).map{ CHARSETS[rand(CHARSETS.size)] }.join
  end

  def self.clean_up_old_url
    logger.info "Kick start clean up job"
    self.where("created_at <= ?", Time.zone.now - 15.days).delete_all
    logger.info "Finished clean up job"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController
  before_action :set_url, only: [:show]

  # GET /urls
  # GET /urls.json
  def index
    @urls = Url.order("created_at desc").all
  end

  # GET /urls/1
  # GET /urls/1.json
  def show
    if @url.present?
      @url.increment!(:count)
      redirect_to @url.origin_url, status: 301
    else
      redirect_to urls_path, notice: "Such url not found!"
    end
  end

  # GET /urls/new
  def new
    @url = Url.new
  end

  # POST /urls
  # POST /urls.json
  def create
    @url = Url.new(url_params)
    respond_to do |format|
      if @url.save
        format.html { redirect_to urls_path, notice: 'Url was successfully created.' }
        format.json { head :ok }
      else
        format.html { render :new }
        format.json { render json: @url.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_url
      @url = Url.where(token: params[:id]).first
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def url_params
      params.require(:url).permit(:origin_url, :token)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/urls_helper.rb
module UrlsHelper
  def display_shorten_url(url)
    request.base_url + "/" + url.token
  end

  def tokened_shorten_url_path(url)
    url_path(id: url.token)
  end
end

app/views/layouts/application.slim
doctype html
html
  head
    meta charset="UTF-8"
    meta[content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport"]
    meta name="renderer" content="webkit"
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    .container
      = yield

app/views/urls/_form.slim
= form_for @url, class: 'form form-horizontal' do |f|
  - if @url.errors.any?
    #error_explanation.alert.alert-danger
      h2
        = pluralize(@url.errors.count, "error")
        |  prohibited this shorten url from being create:
      ul
        - @url.errors.full_messages.each do |message|
          li
            = message
  .form-group
    = f.label :origin_url, class: 'col-md-3 control-label'
    .col-md-9
      = f.text_field :origin_url, class: 'form-control'
      p.help-block Example: http://facebook.com
  .form-group
    = f.label :token, class: 'col-md-3 control-label'
    .col-md-9
      = f.text_field :token, class: 'form-control'
      p.help-block 
        | Optional! you can specify your shorten url here, but limited to 8 charactors.
        br
        | For example: key in 'abcdefgh', then your shorten url would be 
        =request.base_url + "/" + 'abcdefgh'
  .form-actions
    .row
      .col-md-9.col-md-offset-3
        .text-right
          = link_to 'Back', urls_path, class: 'btn btn-default'
          = f.submit class: 'btn btn-primary'

app/views/urls/index.slim
.row
  .col-md-12
    p#notice
      = notice
    h1
      | Urls Shortener
    p.text-right
      = link_to 'Create New Shorten Url', new_url_path, class: 'btn btn-primary'
    table.table.table-hover
      thead
        tr
          th
            | Origin url
          th
            | Shorten url
          th
            | Hit Count
          th
      tbody
        - @urls.each do |url|
          tr
            td
              = url.origin_url
            td
              = display_shorten_url(url)
            td
              = url.count
            td
              = link_to 'Try it now!', tokened_shorten_url_path(url), class: 'btn btn-primary'

app/views/urls/new.slim
.row
  .col-md-12
    h1
      | New Shorten Url
    = render 'form'